site_name: <package-name>
# site_url: http://www.jieyu.ai
repo_url: https://github.com/<github-username>/<package-name>
repo_name: <package-name>
#strict: true
nav:
    -   Home: index.md
    -   Installation: installation.md
    -   Usage: usage.md
    -   Modules: api.md
theme:
    name: material
    language: en
    #logo: assets/logo.png
    palette:
        -   media: "(prefers-color-scheme: light)"
            scheme: default
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   media: "(prefers-color-scheme: dark)"
            scheme: slate
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.instant
        - navigation.tabs.sticky
        - content.code.copy
markdown_extensions:
    -   pymdownx.emoji:
            emoji_index: !!python/name:materialx.emoji.twemoji
            emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.tabbed
    - attr_list
    -   pymdownx.arithmatex:
            generic: true
    -   pymdownx.highlight:
            linenums: true
    - pymdownx.superfences
    - pymdownx.details
    - admonition
    -   toc:
            baselevel: 2
            permalink: true
            slugify: !!python/name:pymdownx.slugs.uslugify
    - meta
plugins:
    - include-markdown
    -   search:
            lang: en
    -   mkdocstrings:
            watch:
                - <package-name-underscore>
extra:
    social:
        -   icon: fontawesome/brands/github
            link: https://github.com/<github-username>
            name: Github
        -   icon: material/email
            link: "mailto:<email>"
    # to enable disqus, uncomment the following and put your disqus id below
    # disqus: disqus_id
    # uncomment the following and put your google tracking id below to enable GA
    #google_analytics:
    #- UA-xxx
    #- auto
